version: '3.5'
services: 
    api:
        hostname: api
        container_name: "api"
        build: source
        volumes:
            - type: bind
              source: ./source
              target: /source
              read_only: true
        ports:
            - 8888:8888
        expose:
          - 8080