version: '3.5'
services: 
    server:
        hostname: api
        build: source
        container_name: "api"
        volumes:
            - type: bind
              source: ./source
              target: /source
              read_only: true
        ports:
            - 8081:8080
        expose:
          - 8080