version: "3.2"
services:

 redis:
    image: "redis:alpine"
    container_name: "redis"
    hostname: redis
    command: redis-server --requirepass pass
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      - REDIS_REPLICATION_MODE=master

